import assert from 'node:assert/strict';
import {BodyView} from './BodyView.js';
import {HeadView} from '../head/HeadView.js';
globalThis.document={hidden:false};globalThis.addEventListener=()=>{};
globalThis.Worker=class{postMessage(){this.sent=(this.sent??0)+1;}terminate(){this.stopped=true;}};
globalThis.createImageBitmap=async()=>({close(){}});
const control=value=>({value,addEventListener(){}});
const video={readyState:2,currentTime:1,videoWidth:640,videoHeight:480};
const head=new HeadView(video,{}, {mode:control('first'),recenter:{},status:{},sensitivity:control('1.5')});
head.worker.onmessage({data:{type:'ready'}});
const body=new BodyView(video,head,{mode:control('seated'),status:{},recenter:control('')});head.body=body;
body.start();body.worker.onmessage({data:{type:'ready'}});
head.completedFrames=1;assert.equal(body.wantsFrame(100),false,'Face gets two frames first');
head.completedFrames=2;assert.equal(body.wantsFrame(100),true);
await head.capture(100);assert.equal(head.busy,false,'Head yields the earned body slot');
await body.capture(100);assert.equal(body.busy,true);assert.equal(body.worker.sent,1);
await head.capture(140);assert.equal(head.busy,false,'Face does not overlap body inference');
body.worker.onmessage({data:{type:'pose',ts:performance.now(),pose:null}});
await head.capture(150);assert.equal(head.busy,true,'Face resumes after body finishes');
head.busy=false;head.completedFrames=4;video.currentTime=2;
assert.equal(body.wantsFrame(166),true,'Body is not starved by slow face inference');
body.enabled=false;assert.equal(body.wantsFrame(166),false);
body.enabled=true;head.mode='off';assert.equal(body.wantsFrame(166),false);
head.mode='first';head.performance.latency=80;
assert.equal(body.wantsFrame(180),false,'Slow devices reduce body rate');
assert.equal(body.wantsFrame(230),true);
document.hidden=true;assert.equal(body.wantsFrame(230),false);
body.stop();head.worker.terminate();clearTimeout(head.timer);
console.log('PASS: two-face/one-body scheduling, no concurrent inference, no CPU starvation, pause/off/background and adaptive rate');
